
name: Build project
on:
  push:
    branches-ignore:
      - master
      - testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: cp .env.local.example .env.local

      - run: npm ci && npm run build
