name: Deploy PR preview to Layer0

on:
  pull_request:
    branches:
      - testing

jobs:

  deploy-to-layer0:
    # cancels the deployment for the automatic merge push created when tagging a release
    if: contains(github.ref, 'refs/tags') == false || github.event_name == 'release'
    runs-on: ubuntu-latest
    env:
      deploy_token: ${{secrets.LAYER0_DEPLOY_TOKEN}}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14.18.1
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install packages
        run: npm ci # if using npm for your project
        #  run: rm -rf node_modules && yarn install --frozen-lockfile # if using yarn for your project
      - name: Deploy to Layer0
        run: |
          npm run layer0:deploy collabamigo -- --token=$deploy_token  --environment=default --site=devcollabamigo
        env:
          deploy_token: ${{secrets.LAYER0_DEPLOY_TOKEN_PREVIEW}}

      - run : echo "::set-output name=deploy_output::$(cat .layer0/deployment-manifest.json)"
        id: set-output-deploy-output

      - name: JSON processing
        run: |
          echo "${{fromJson(steps.set-output-deploy-output.outputs.deploy_output).url}}"

      - name: "Comment preview URL on Pull Request"
        uses: actions/github-script@v5
        env:
          PREVIEW_URL: ${{ steps.deploy.outputs.PREVIEW_URL }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The preview URL for this PR is ${{fromJson(steps.set-output-deploy-output.outputs.deploy_output).url}}'
            })
