
name: Deploy to Development
on:
  push:
    branches:
      - testing
jobs:
  build_and_deploy:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing yarn
        run: npm install -g yarn

#      - name: Installing dependencies
#        run: yarn install --immutable

      - name: ESLinting .js and .jsx files
        run: yarn run eslint src --ext .js,.jsx

      - name: Building
        run: yarn build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          target: testing
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COLLABAMIGO_TESTING }}'
          channelId: live
          projectId: testing
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
  Create-issues-using-TODO:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 2

      - name: Github login
        run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token

      - name: Creating issues
        run: readarray -t array <<< $(git diff HEAD^ --name-only -G "TODO" -- ':!:*.yml' | xargs --no-run-if-empty git
                grep -n "TODO" --) && for command in "${array[@]}"; do
                    gh issue create --title "${command##*:}" --body "${command}" --label "todo" || echo "ERROR ${command}";
                      done

      - name: Github logout
        run: gh auth logout --hostname github.com
