name: Deploy to Preview Channel

on:
  push:
    branches: [ main, testing, testing-pragyan ]
  pull_request:
    branches: [ main, testing ]

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npm ci && npx eslint src && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COLLABAMIGO_PREVIEW }}'
          expires: 30d
          projectId: preview
