name: Deploy to Preview Channel

on:
  pull_request:
    branches:
      - testing

jobs:
  vercel:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '16.8.0'
          registry-url: https://registry.npmjs.org/

      - name: "Deploy to Vercel"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: echo "::set-output name=PREVIEW_URL::$(npx vercel --token "${VERCEL_TOKEN}" --prod)"

      - name: "Temp"
        env:
          tag_name: ${{ steps.version.outputs.TAG_NAME }}
        run: echo ${{ tag_name }}

#      - uses: actions/github-script@v5
#        with:
#          script: |
#            github.rest.issues.createComment({
#              issue_number: context.issue.number,
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              body: '👋 Thanks for reporting!'
#            })
