name: Deploy to Development
on:
  push:
    branches:
      - testing
jobs:
  build:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing dependencies
        run: npm ci

      - name: Building
        run: npm run build

      - name: Upload build result
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: out

  eslint:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing dependencies
        run: npm ci

      - name: ESLinting .js and .jsx files
        run: npx eslint src --ext .js,.jsx

  deploy:
    environment: testing
    runs-on: ubuntu-latest
    needs: [build, eslint]
    steps:
      - uses: actions/checkout@v2

      - name: Download build result
        uses: actions/download-artifact@v2
        with:
          name: build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          target: testing
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COLLABAMIGO_TESTING }}'
          channelId: live
          projectId: testing
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
