name: Deploy to Development
on:
  push:
    branches:
      - testing
jobs:
  vercel:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '16.8.0'
          registry-url: https://registry.npmjs.org/

      - name: "Deploy to Vercel"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: npx vercel --token "${VERCEL_TOKEN}" --prod
