name: Deploy to Preview Channel

on:
  pull_request:
    branches:
      - testing

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Installing dependencies
        run: npm ci

      - name: ESLinting .js and .jsx files
        run: npm run eslint src --ext .js,.jsx

      - name: Building
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          target: preview
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COLLABAMIGO_PREVIEW }}'
          expires: 30d
          projectId: preview
