
name: Deploy to Production
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Putting backend main url in file
        run: sed -i "1s|.*|const backend='https://mysterious-savannah-09391.herokuapp.com/'|" src/env.js
      - run: npm ci && npx eslint src && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          target: production
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COLLABAMIGO_PRODUCTION }}'
          channelId: live
          projectId: default
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
